### ISSUE TITLE
How to Upgrade

### ISSUE THREAD

**Issue by kamaldua65** [codeurjc-students/2019-OpenViduTeaching#19]
I installed version 0.3.2 few months back using docker-override.yml ( using with openvidu version 2.15.0 now)
I tried but I cant update to latest version.
my yml file is:
version: '3.1'

services:
    app:
       image: diegomzmn/openviduteaching:latest
       restart: on-failure
       volumes:
             - ${LOCAL_INITIAL_FILE_PATH}:${DOCKER_INITIAL_FILE_PATH}
             - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
       ports:
             - "5442:8080"
       environment:
             OPENVIDU_URL: https://${DOMAIN_OR_PUBLIC_IP}
             OPENVIDU_SECRET: ${OPENVIDU_SECRET}
             INITIAL_DATA_FILE: ${DOCKER_INITIAL_FILE_PATH}
             OPENVIDU_RECORDING: ${OPENVIDU_RECORDING}
             OPENVIDU_RECORDING_PATH: ${OPENVIDU_RECORDING_PATH}

**Comment by kamaldua65** [comment]
I have manged to upgrade it, however still have issue running it. 
When I load it on front end it shows a blank page, When I look at source, problem seems to be it has:
<base href="http://localhost:8080/">

It is running on openvidu 2.15 ,My new docker-override file is:
version: '3.1'

services:
    app:
       image: diegomzmn/openviduteaching:latest
       restart: on-failure
       network_mode: host
       volumes:
             - ${LOCAL_INITIAL_FILE_PATH}:${DOCKER_INITIAL_FILE_PATH}
             - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
       environment:
             - SERVER_PORT=5442
             - OPENVIDU_URL=http://localhost:5443
             - OPENVIDU_SECRET= ${OPENVIDU_SECRET}
             - INITIAL_DATA_FILE= ${DOCKER_INITIAL_FILE_PATH}
             - OPENVIDU_RECORDING= ${OPENVIDU_RECORDING}
             - OPENVIDU_RECORDING_PATH= ${OPENVIDU_RECORDING_PATH}

**Comment by DiegoMzmn** [comment]
Can you post what the browser console displays?

**Comment by kamaldua65** [comment]
![image](https://user-images.githubusercontent.com/3298223/91124562-aa685280-e6c9-11ea-8588-afe5a4b7a1bc.png)

It tries to connect to localhost:8080

And page source is as follows, I think it is due to  base href="http://localhost:8080/">
![image](https://user-images.githubusercontent.com/3298223/91124768-2fec0280-e6ca-11ea-9e8b-8d37fcf0be59.png)

**Comment by DiegoMzmn** [comment]
I see. Using `ports: -"5442:8080"` in the yml instead of setting the server port to 5442 should work. If you want the port to be 5442 or cannot make it work otherwise I suggest you create the docker image yourself using either of the image creating scripts ("create_image.sh" or "create_image.cmd") after changing the href port in them.

**Comment by kamaldua65** [comment]
Actually I already tried with ports option 5442:8080 but it did not work.I will try to build myself.Thanks for support.On 25 Aug 2020 17:04, Diego Muñoz Martín <notifications@github.com> wrote:
I see. Using
ports:
"5442:8080"
in the yml instead of setting the server port to 5442 should work. If you want the port to be 5442 or cannot make it work otherwise I suggest you create the docker image yourself using either of the image creating scripts ("create_image.sh" or "create_image.cmd") after changing the href port in them.

**Comment by kamaldua65** [comment]
issue is not with port but it is issue with base base href:
I compared index.html in jar file of 0.3.1 with 1.3.0
version 0.3.1 have
  <title>OpenviduTeaching</title>
base href="/"
while version 1.3.0 index.html file is:
base href="http://localhost:8080

hence it will never work except local machine.

May be you can correct same in next version.
