### ISSUE TITLE
can't deploy using the jar file

### ISSUE THREAD

**Issue by alex-ciorita** [codeurjc-students/2019-OpenViduTeaching#3]
When I run the docker container, everything works fine, but when I try to deploy the jar file, things break (I'm not familiar with java so I don't even know where to start looking).

This works:
docker run -p 8080:8080 -e openvidu.url="https://abc.octasoftware.ro:4443/" -e openvidu.secret=MY_SECRET -e initialDataFile="/initialData.json" -v /home/ubuntu/dev/openvidu/initialData.json:/initialData.json --rm diegomzmn/openviduteaching

This doesn't:
java -jar OpenViduTeaching-0.3.0.jar --initialDataFile="/home/ubuntu/dev/openvidu/initialData.json" --openvidu.url="https://abc.octasoftware.ro:4443/" --openvidu.secret="MY_SECRET"

Log file attached. Thanks a lot!
[ovt.log](https://github.com/codeurjc-students/2019-OpenViduTeaching/files/4691757/ovt.log)

**Comment by DiegoMzmn** [comment]
It looks like there was an incompatibility with newer versions of Java. I just made a new release that should fix it.
Also the format of the enviroment variables was changed so take a look at the documentation again to fix them.
