### ISSUE TITLE
Go back from recording view

### ISSUE THREAD

**Issue by CSantosM** [codeurjc-students/2019-OpenViduTeaching#5]
Testing OpenViduTeaching version 1.2.0.

After do login in the app and go to recorded videos page of a room, I can't go back to the main page (where the rooms list appeared).

**Comment by cruizba** [comment]
@CSantosM is master version. We've built the docker image from master branch.

**Comment by DiegoMzmn** [comment]
If you mean the page where the video of a recording is displayed, you can click the OpenVidu logo on the top left (as long as you are not in fullscreen mode), which will take to the main page.
