### ISSUE TITLE
Docker image for version 1.2.0 is missing

### ISSUE THREAD

**Issue by cruizba** [codeurjc-students/2019-OpenViduTeaching#7]
# Docker image for version 1.2.0 is missing
Not a real problem :), but it would be great to have docker image tag for 1.3.0 as `diegomzmn/openviduteaching:1.3.0`

Great project!

Regards,
Carlos

**Comment by DiegoMzmn** [comment]
I forgot to upload the images to Docker Hub with the release, sorry.  They are available now.
